In [12]:
#import the necessary libraries and functions/methods
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from warnings import simplefilter


stock = pd.read_csv('Stock_portfolio_data.csv')

date_time_format = stock.set_index(pd.to_datetime(stock["Date"], format='%Y%m%d'))
# set the dataframe's date column to be in date time format.


stock_last_4 = date_time_format.loc["2015-07-31":"2018-07-31"]

print(stock_last_4)

                Date  0111145D US Equity  0202445Q US Equity  \
Date
2015-07-31  20150731                 NaN                 NaN
2015-08-01  20150801                 NaN                 NaN
2015-08-02  20150802                 NaN                 NaN
2015-08-03  20150803                 NaN                 NaN
2015-08-04  20150804                 NaN                 NaN
...              ...                 ...                 ...
2018-07-27  20180727                 NaN                 NaN
2018-07-28  20180728                 NaN                 NaN
2018-07-29  20180729                 NaN                 NaN
2018-07-30  20180730                 NaN                 NaN
2018-07-31  20180731                 NaN                 NaN

            0203524D US Equity  0226226D US Equity  0376152D US Equity  \
Date
2015-07-31                 NaN                 NaN                 NaN
2015-08-01                 NaN                 NaN                 NaN
2015-08-02                 NaN                 NaN                 NaN
2015-08-03                 NaN                 NaN                 NaN
2015-08-04                 NaN                 NaN                 NaN
...                        ...                 ...                 ...
2018-07-27                 NaN                 NaN                 NaN
2018-07-28                 NaN                 NaN                 NaN
2018-07-29                 NaN                 NaN                 NaN
2018-07-30                 NaN                 NaN                 NaN
2018-07-31                 NaN                 NaN                 NaN

            0440296D US Equity  0544749D US Equity  0574018D US Equity  \
Date
2015-07-31                 NaN                 NaN                 NaN
2015-08-01                 NaN                 NaN                 NaN
2015-08-02                 NaN                 NaN                 NaN
2015-08-03                 NaN                 NaN                 NaN
2015-08-04                 NaN                 NaN                 NaN
...                        ...                 ...                 ...
2018-07-27                 NaN                 NaN                 NaN
2018-07-28                 NaN                 NaN                 NaN
2018-07-29                 NaN                 NaN                 NaN
2018-07-30                 NaN                 NaN                 NaN
2018-07-31                 NaN                 NaN                 NaN

            0598884D US Equity  ...  YNR US Equity  YRCW US Equity  \
Date                            ...
2015-07-31                 NaN  ...            NaN           19.30
2015-08-01                 NaN  ...            NaN           19.30
2015-08-02                 NaN  ...            NaN           19.30
2015-08-03                 NaN  ...            NaN           20.46
2015-08-04                 NaN  ...            NaN           20.54
...                        ...  ...            ...             ...
2018-07-27                 NaN  ...            NaN            9.76
2018-07-28                 NaN  ...            NaN            9.76
2018-07-29                 NaN  ...            NaN            9.76
2018-07-30                 NaN  ...            NaN            9.45
2018-07-31                 NaN  ...            NaN            9.74

            YUM US Equity  YUMC US Equity  ZBH US Equity  ZETHQ US Equity  \
Date
2015-07-31        59.4110             NaN       101.2722              NaN
2015-08-01        59.4110             NaN       101.2722              NaN
2015-08-02        59.4110             NaN       101.2722              NaN
2015-08-03        59.4517             NaN       101.5252              NaN
2015-08-04        59.7021             NaN       100.3574              NaN
...                   ...             ...            ...              ...
2018-07-27        78.5726         37.1063       125.9671              NaN
2018-07-28        78.5726         37.1063       125.9671              NaN
2018-07-29        78.5726         37.1063       125.9671              NaN
2018-07-30        78.4033         35.9496       126.2765              NaN
2018-07-31        78.9510         35.9795       125.2883              NaN

            ZION US Equity  ZRN US Equity  ZTS US Equity  ZTS-W US Equity
Date
2015-07-31         29.8522            NaN        47.7670              NaN
2015-08-01         29.8522            NaN        47.7670              NaN
2015-08-02         29.8522            NaN        47.7670              NaN
2015-08-03         29.5172            NaN        47.2794              NaN
2015-08-04         29.5076            NaN        47.6402              NaN
...                    ...            ...            ...              ...
2018-07-27         51.0787            NaN        85.0837              NaN
2018-07-28         51.0787            NaN        85.0837              NaN
2018-07-29         51.0787            NaN        85.0837              NaN
2018-07-30         51.7706            NaN        84.3746              NaN
2018-07-31         51.0985            NaN        86.3619              NaN

[1097 rows x 1200 columns]

In [13]:
stock_cleaned = stock_last_4.dropna(axis=1, how='any')

stats = stock_cleaned.describe()
# Find certain characteristics and details about some of the stock such as its variance/volatility or stability.

without_date = stats.drop('Date', axis=1)

# Find the column index (or name) where each row has the maximum value
max_column_indices = without_date.idxmax(axis=1)

print(max_column_indices)

#The below information means that YRCW US Equity stock has the highest mean and standard deviation value among all other stocks
#within the 1993 to 1997 time period, not standardized

count       A US Equity
mean     BKNG US Equity
std      AMZN US Equity
min      BKNG US Equity
25%      BKNG US Equity
50%      BKNG US Equity
75%      BKNG US Equity
max      BKNG US Equity
dtype: object

In [14]:
stats

,Date,A US Equity,AA US Equity,AAL US Equity,AAP US Equity,AAPL US Equity,ABBV US Equity,ABC US Equity,ABMD US Equity,ABT US Equity,...,XLNX US Equity,XOM US Equity,XRAY US Equity,XRX US Equity,XYL US Equity,YRCW US Equity,YUM US Equity,ZBH US Equity,ZION US Equity,ZTS US Equity
count,1.097000e+03,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,...,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000,1097.000000
mean,2.016646e+07,51.703608,32.628228,42.889278,140.179076,131.755123,69.044950,85.158890,158.882530,46.076101,...,55.701099,76.607550,57.991537,26.224695,51.721322,11.948765,65.704656,112.219077,37.834192,57.933887
std,9.402142e+03,11.916598,11.761049,6.240757,27.673918,31.658537,18.862032,7.530593,91.030615,8.565605,...,11.008178,4.791582,5.371253,2.747413,13.628889,2.698477,11.494444,10.120934,10.931286,14.165453
min,2.015073e+07,32.404700,14.942500,24.677700,79.228000,86.678200,43.154500,66.365600,70.400000,34.235200,...,35.993300,60.857600,42.108700,20.853000,29.064100,6.760000,44.753800,89.616400,19.123100,38.578600
25%,2.016043e+07,40.819600,21.330600,38.669500,116.293000,104.628400,55.637700,79.848100,99.310000,39.197600,...,44.729700,74.013000,55.916200,23.895400,40.844900,9.770000,56.554200,102.245600,27.181000,46.581300
50%,2.017013e+07,47.930100,31.630000,42.879400,145.988000,118.244700,60.498000,84.733900,122.460000,42.676900,...,55.995900,77.019200,59.162600,26.257700,49.343800,11.610000,62.686900,114.071700,39.784700,52.827500
75%,2.017103e+07,63.715100,44.420000,47.134000,160.454000,160.062900,88.325700,90.550900,181.070000,53.813800,...,66.125700,79.887500,61.720700,28.003200,65.010700,13.640000,75.830500,119.675800,45.646500,65.448700
max,2.018073e+07,74.316200,60.230000,57.910200,199.310000,193.464100,119.436300,103.685600,446.210000,65.391100,...,75.974700,86.475900,68.076300,33.181700,78.775900,20.890000,86.354100,131.249500,57.858900,88.947600

In [15]:


stocks_return_percent = stock_cleaned.pct_change().dropna()
# Convert the dataframe to have the daily percentage change for each stock.

stocks_return_percent = stocks_return_percent.drop('Date', axis=1)
# Drop the date

In [16]:
stocks_return_percent

,A US Equity,AA US Equity,AAL US Equity,AAP US Equity,AAPL US Equity,ABBV US Equity,ABC US Equity,ABMD US Equity,ABT US Equity,ABX US Equity,...,XLNX US Equity,XOM US Equity,XRAY US Equity,XRX US Equity,XYL US Equity,YRCW US Equity,YUM US Equity,ZBH US Equity,ZION US Equity,ZTS US Equity
Date,,,,,,,,,,,,,,,,,,,,,
2015-08-01,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2015-08-02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2015-08-03,0.001221,-0.023303,0.040150,-0.002298,-0.023578,-0.003999,0.000662,-0.000775,-0.003747,-0.050991,...,0.003593,-0.014518,-0.016868,-0.007260,-0.019692,0.060104,0.000685,0.002498,-0.011222,-0.010208
2015-08-04,-0.009267,0.009337,0.024693,0.007418,-0.032085,0.003154,0.003685,0.147287,0.000198,0.014929,...,0.001925,-0.011402,-0.001252,0.005483,-0.003248,0.003910,0.004212,-0.011503,-0.000325,0.007631
2015-08-05,0.002461,0.006186,0.005148,0.000976,0.006630,0.005004,0.009793,0.046059,-0.000593,-0.038246,...,0.024956,0.000000,0.010022,-0.000910,0.004445,0.017040,0.009640,0.007273,0.013302,-0.004912
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-07-27,-0.014981,0.009341,-0.008248,-0.013610,-0.016631,-0.035980,-0.003843,-0.039145,-0.006091,0.011718,...,-0.008189,-0.027540,0.006171,-0.003893,-0.001850,-0.023023,-0.000506,0.077619,-0.000194,-0.003974
2018-07-28,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2018-07-29,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2018-07-30,-0.017034,-0.014808,-0.018139,0.005930,-0.005602,0.009828,-0.000122,-0.034537,-0.001380,-0.007126,...,-0.013264,-0.002198,0.008673,0.005471,-0.002279,-0.031762,-0.002155,0.002456,0.013546,-0.008334
2018-07-31,0.021816,0.016205,0.014625,0.003911,0.002001,0.008529,-0.013026,-0.005303,0.005678,0.003589,...,-0.011386,-0.002814,0.008806,0.009328,0.093245,0.030688,0.006986,-0.007826,-0.012982,0.023553

In [17]:
mean_stock_return_pct = stocks_return_percent.mean()
# Find the average daily percentage change for each stock.

top_10_returns = mean_stock_return_pct.nlargest(10)
# determine the top 5 stocks that have the highest average percentage return for each day.

print(top_10_returns)

top_10_returns_bad = mean_stock_return_pct.nsmallest(10)
# do the same but with top 5 worst stocks

print(top_10_returns_bad)

AMD US Equity     0.002637
SKY US Equity     0.002598
NVDA US Equity    0.002548
CLF US Equity     0.002240
NKTR US Equity    0.001896
ALGN US Equity    0.001736
ABMD US Equity    0.001615
DNR US Equity     0.001549
NAV US Equity     0.001385
NC US Equity      0.001334
dtype: float64
SUNEQ US Equity   -0.002452
FTR US Equity     -0.001541
ENDP US Equity    -0.001101
WIN US Equity     -0.001082
MNK US Equity     -0.001068
RRD US Equity     -0.001043
BBBY US Equity    -0.000935
RAD US Equity     -0.000904
JCP US Equity     -0.000727
GME US Equity     -0.000680
dtype: float64

In [18]:

std_pct_dailychange =  stocks_return_percent.std()
# Now try and find the standard deviation/risk/volatility for each stock.

sharpe_ratio = mean_stock_return_pct/std_pct_dailychange
# Find the sharpe ratio for each stock.

top_10_std = std_pct_dailychange.nlargest(10)
# Find top 5 most volatile stocks.

top_10_sharpe_ratio = sharpe_ratio.nlargest(10)
# Find top 5 best sharpe ratio stocks within the 1993 to 1997 time frame.

In [19]:
print(top_10_std)

SUNEQ US Equity    0.101343
DNR US Equity      0.053814
CLF US Equity      0.043353
FOSL US Equity     0.043055
CHK US Equity      0.042154
NL US Equity       0.040364
SKY US Equity      0.038266
ENDP US Equity     0.035976
FNMA US Equity     0.035860
FMCC US Equity     0.035234
dtype: float64

In [20]:
print(top_10_sharpe_ratio)

NVDA US Equity    0.114602
CPRT US Equity    0.102096
ALGN US Equity    0.100159
IDXX US Equity    0.087255
ISRG US Equity    0.087094
CTAS US Equity    0.086119
AMZN US Equity    0.084674
ADBE US Equity    0.083041
MSCI US Equity    0.081902
BR US Equity      0.081686
dtype: float64

In [21]:
# Since we now know the top 10 stocks with the highest sharpe ratio, we can now assign the respective weightings for
# each stock.

In [22]:
top_10_sharpe_ratio = pd.DataFrame(top_10_sharpe_ratio)

total_sharpe_ratio = top_10_sharpe_ratio[0].sum()

In [23]:

top_10_sharpe_ratio['proportion weightage in portfolio %'] = top_10_sharpe_ratio[0] / total_sharpe_ratio * 100

In [24]:
top_10_sharpe_ratio.rename(columns={0: 'Sharpe Ratio'}, inplace=True)

In [25]:
top_10_sharpe_ratio

                Sharpe Ratio  proportion weightage in portfolio %
NVDA US Equity      0.114602                            12.612642
CPRT US Equity      0.102096                            11.236321
ALGN US Equity      0.100159                            11.023112
IDXX US Equity      0.087255                             9.602951
ISRG US Equity      0.087094                             9.585185
CTAS US Equity      0.086119                             9.477887
AMZN US Equity      0.084674                             9.318923
ADBE US Equity      0.083041                             9.139135
MSCI US Equity      0.081902                             9.013786
BR US Equity        0.081686                             8.990059

In [86]:
# $10,000 is how much money we get to put into our portfolio. We chose 10 stock instead of 5 or a lower number in order to
# diversify our portfolio thus lower the risk.
# Therefore: 

# NVDA: $1261, NVDA Stock price on 
# CPRT: $1123
# ALGN: $1102
# IDXX: $960
# ISRG: $959
# CTAS: $950
# AMZN: $930
# ADBE: $910
# MSCI: $901
# BR: $ 899

stock_last_1 = date_time_format.loc["2018-08-01":"2019-07-01"]
# Now lets find the respective prices of each stock on the first and last day of the test year.

stock_last_1 = stock_last_1[['NVDA US Equity', 'CPRT US Equity', 'ALGN US Equity', 'IDXX US Equity', 'ISRG US Equity', 'CTAS US Equity', 'AMZN US Equity', 'ADBE US Equity', 'MSCI US Equity', 'BR US Equity']]


# First and last entries for each stock
nvidia_start = stock_last_1['NVDA US Equity'].iloc[0]
nvidia_last = stock_last_1['NVDA US Equity'].iloc[-1]
nvidia_diff = nvidia_last - nvidia_start

CPRT_start = stock_last_1['CPRT US Equity'].iloc[0]
CPRT_last = stock_last_1['CPRT US Equity'].iloc[-1]
CPRT_diff = CPRT_last - CPRT_start

ALGN_start = stock_last_1['ALGN US Equity'].iloc[0]
ALGN_last = stock_last_1['ALGN US Equity'].iloc[-1]
ALGN_diff = ALGN_last - ALGN_start

IDXX_start = stock_last_1['IDXX US Equity'].iloc[0]
IDXX_last = stock_last_1['IDXX US Equity'].iloc[-1]
IDXX_diff = IDXX_last - IDXX_start

ISRG_start = stock_last_1['ISRG US Equity'].iloc[0]
ISRG_last = stock_last_1['ISRG US Equity'].iloc[-1]
ISRG_diff = ISRG_last - ISRG_start

CTAS_start = stock_last_1['CTAS US Equity'].iloc[0]
CTAS_last = stock_last_1['CTAS US Equity'].iloc[-1]
CTAS_diff = CTAS_last - CTAS_start

AMZN_start = stock_last_1['AMZN US Equity'].iloc[0]
AMZN_last = stock_last_1['AMZN US Equity'].iloc[-1]
AMZN_diff = AMZN_last - AMZN_start

ADBE_start = stock_last_1['ADBE US Equity'].iloc[0]
ADBE_last = stock_last_1['ADBE US Equity'].iloc[-1]
ADBE_diff = ADBE_last - ADBE_start

MSCI_start = stock_last_1['MSCI US Equity'].iloc[0]
MSCI_last = stock_last_1['MSCI US Equity'].iloc[-1]
MSCI_diff = MSCI_last - MSCI_start

BR_start = stock_last_1['BR US Equity'].iloc[0]
BR_last = stock_last_1['BR US Equity'].iloc[-1]
BR_diff = BR_last - BR_start

#Number of each stock bought at the start
nvidia_stock_count = 1261/nvidia_start
CPRT_stock_count = 1123/CPRT_start
ALGN_stock_count = 1102/ALGN_start
IDXX_stock_count = 960/IDXX_start
ISRG_stock_count = 959/ISRG_start
CTAS_stock_count = 950/CTAS_start
AMZN_stock_count = 930/AMZN_start
ADBE_stock_count = 910/ADBE_start
MSCI_stock_count = 901/MSCI_start
BR_stock_count = 899/BR_start

#total profit made
profit = nvidia_stock_count*nvidia_diff + CPRT_stock_count*CPRT_diff + ALGN_stock_count*ALGN_diff + IDXX_stock_count*IDXX_diff
+ ISRG_stock_count*ISRG_diff + CTAS_stock_count*CTAS_diff + AMZN_stock_count*AMZN_diff + ADBE_stock_count*ADBE_diff 
+ MSCI_stock_count*MSCI_diff + BR_stock_count*BR_diff

print(profit)

-147.58727673272932

In [114]:
print(nvidia_diff)
print(CPRT_diff)
print(ALGN_diff)
print(IDXX_diff)
print(ISRG_diff)
print(CTAS_diff)
print(AMZN_diff)
print(ADBE_diff)
print(MSCI_diff)
print(BR_diff)

-80.1653
17.4
-82.01999999999998
44.01000000000002
13.019999999999982
35.2277
125.01999999999998
52.960000000000036
78.69049999999999
17.206400000000002

In [115]:
# Now lets do static relative weights, change the weightages of each stock every 3 months to maintain the initial weightages of each stock.
# Assume that `prices` is your DataFrame with daily prices for each stock.


initial_weights1 = [0.115, 0.102, 0.100, 0.087, 0.087, 0.086, 0.085, 0.083, 0.082, 0.082]

def calculate_portfolio_profit(prices, initial_weights):
    initial_weights = np.array(initial_weights)

    # Rebalance dates every 3 months
    rebalance_dates = ['2018-11-01', '2019-02-01', '2019-05-01',
               '2019-08-01']

    # Track portfolio value over time
    portfolio_value = pd.Series(index=prices.index, dtype=float)
    initial_money = 10000  
    # The starting prices of each stock 
    start_prices = prices.iloc[0]
    dollar_allocation = initial_money * initial_weights 
    
    # Holdings is the number of shares you have of each stock
    holdings = dollar_allocation / start_prices
    
    # Calculate how much money is in your portfolio on the day right before rebalancing it for the first time.
    current_money = holdings * prices.loc['2018-11-01']

    for i, date in enumerate(rebalance_dates):
        # Define the rebalancing period
        start_date = date
        end_date = rebalance_dates[i+1] if i+1 < len(rebalance_dates) else prices.index[-1]
        period_prices = prices.loc[start_date:end_date]
        
        if period_prices.empty:
            continue
        
        # Get prices at the start of the period
        start_prices = period_prices.iloc[0]

        # Rebalance: Calculate how many shares to buy for each stock
        dollar_allocation = current_money * initial_weights
        holdings = dollar_allocation / start_prices

        # Calculate portfolio value for the period
        for day in period_prices.index:
            day_prices = prices.loc[day]
            portfolio_value[day] = np.sum(holdings * day_prices)

        # Update current value for the next rebalance
        current_money = portfolio_value.loc[period_prices.index[-1]]

    # Profit is final portfolio value - initial capital
    final_value = portfolio_value.dropna().iloc[-1]
    profit = final_value - initial_money

    return (profit, portfolio_value)

port_valueprofit = calculate_portfolio_profit(stock_last_1, initial_weights1)

In [116]:
print(port_valueprofit)

(-9262.11154743669, Date
2018-08-01           NaN
2018-08-02           NaN
2018-08-03           NaN
2018-08-04           NaN
2018-08-05           NaN
                 ...
2019-06-27    724.622710
2019-06-28    730.781105
2019-06-29    730.781105
2019-06-30    730.781105
2019-07-01    737.888453
Length: 335, dtype: float64)

In [ ]:
# As you can see from the above results, static relative weights perform much worse than just static weights. 
# A possible explanation for this is: If you invest a large percentage of your portfolio into stocks that perform
# very poorly, rebalancing your portfolio every 3 months to maintain the initial percentage of those badly performing stocks in your portfolio
# will drastically decrease its value. The value of your portfolio will decrease much faster than if you
# just use static weights, because there is no rebalancing done in the case that your stocks do very poorly.